services:
  - type: web
    name: favLearnAI-backend
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    plan: free
    autoDeploy: true
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
    buildFilter:
      paths:
        - backend/**
    rootDir: backend
